### ISSUE TITLE
Updater fails

### ISSUE THREAD

**Issue by eSaner** [sterner-stuff/private-wordpress-plugin-composer-provider#1]
Would love to get this working with ACF Pro, but the action keeps failing. I cloned your repo to my local machine, then rm -r .git, and added the ACF Pro download link to update.yml.

`# Fetch latest version
      - name: Fetch
        run: wget 'https://connect.advancedcustomfields.com/index.php?a=download&p=pro&k=${{secrets.ACF_PRO_KEY}}' -O plugin.zip`

Then I updated the composer.json file, copying from your readme.md example, and commited and pushed up to a new private repo on Github. Then I created an action secret in the repo named ACF_PRO_KEY with my key as the value.

Every time the action runs it fails. If I copy/paste the fetch url with the key value into a browser the plugin downloads properly. Am I missing something?

**Comment by ethanclevenger91** [comment]
I forgot to put this in the readme -

If there isn't a new version of the plugin available, the action will technically "fail" because there's no way to short-circuit a GitHub action without triggering a fail state. The best you can do seems to be wrap all subsequent steps around an "if" statement. That's something that could be improved.

It's also possible it'll fail if there are no existing tags. When I tested, I started with a version of ACF already committed and tagged.

**Comment by ethanclevenger91** [comment]
Yeah, from the action that gets the latest tag:

> This action has only one output, namely, tag for the latest tag this action finds. When no tag is found or another error occurs it exits with code 1

So that logic needs updated to handle that case.

**Comment by eSaner** [comment]
Ah ha, I need to start with a tagged version of ACF. That would be a helpful addition to the readme as well.

I get an email every time it fails, which will be quite often between ACF releases. I don't see a way to disable those notifications in Github, so reducing the failure frequency with some improved logic would be helpful.

**Comment by ethanclevenger91** [comment]
@eSaner I just pushed a pretty substantial update to `update.yml` that does a couple things:

- Wraps later steps in a check for whether or not a newer version was found, preventing the "fail" state when there simply wasn't an update required
- Allows configuring an env var for the plugin's slug, because it's likely that some files need moved up a directory after unzipping

The readme also now recommends, after cloning and copying the repo, simply running `git tag 0.0.0 && git push --tags`, which will create a state that the previous tag detector won't fail about.

**Comment by eSaner** [comment]
Awesome. I'll test it and report back.

**Comment by ethanclevenger91** [comment]
@eSaner added a couple functional examples [here](https://github.com/sterner-stuff/private-wordpress-plugin-composer-provider/tree/main/.github/workflows/examples). I'm going to close this issue in the meantime since the non-stop fails and tag issues were sorted out.

**Comment by eSaner** [comment]
Working now. This is super helpful. Thanks!
